### ISSUE TITLE
'CHART_X_MR_X' is not defined

### ISSUE THREAD

**Issue by hnguyen9** [torstenfeld/python-controlchart#5]
NameError                                 Traceback (most recent call last)
<ipython-input-15-80a6239d9d3f> in <module>
      1 import controlchart
      2 from controlchart import Spc
----> 3 s = Spc([1, 2, 3, 3, 2, 1, 3, 8], CHART_X_MR_X)

NameError: name 'CHART_X_MR_X' is not defined

I used the same code shown in the usage and encounter the above issue. Can you help me to check on python 3.6? Thank you.

**Comment by torstenfeld** [comment]
Try ```from controlchart import Spc, CHART_X_MR_X```
instead. For the python3 issue, I just uploaded a new version (0.2.0) with python3 support to pypi.
